### DISCUSSION TITLE
fail connecting apm-server to kibana

### DISCUSSION THREAD

**Discussion by zeihanaulia** [sherifabdlnaby/elastdocker#81] [General]
Ask a question...

I want to add apm-server to this stack, so I try to add a new service 

```yaml
  apm-server:
    image: docker.elastic.co/apm/apm-server:${ELK_VERSION}
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=https://kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=https://kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - kibana
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
```
all services running and apm-server is correctly setup.

![Screenshot 2022-07-20 041410](https://user-images.githubusercontent.com/5449841/179849982-1cde72b2-7e33-4e97-81e6-bee8ab5972cf.png)

![Screenshot 2022-07-20 041742](https://user-images.githubusercontent.com/5449841/179850202-d34fd2ed-5583-4fb8-ac63-4eb61e6ba0cf.png)

the problem is there's no data in APM services or traces, this is my code

```go
package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
	"go.elastic.co/apm/module/apmgorilla"
	"go.elastic.co/apm/v2"
)

func helloHandler(w http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	span, ctx := apm.StartSpan(ctx, "helloHandler", "custom")
	defer span.End()

	fmt.Fprint(w, greet(ctx, mux.Vars(req)["name"]))
}

func greet(ctx context.Context, name string) string {
	span, _ := apm.StartSpan(ctx, "greet", "custom")
	defer span.End()

	return fmt.Sprintf("Hello, %s! from span handler\n", name)
}

func main() {
	r := mux.NewRouter()
	r.Use(apmgorilla.Middleware())
	r.HandleFunc("/hello/{name}", helloHandler)
	log.Fatal(http.ListenAndServe(":8000", r))
}
```

application apm debug
![Screenshot 2022-07-20 042636](https://user-images.githubusercontent.com/5449841/179851489-5eda7308-1aea-495d-a6d2-1b173c2146ee.png)

this logs error from apm-server

![Screenshot 2022-07-20 042231](https://user-images.githubusercontent.com/5449841/179850866-346c60ce-2e3e-461f-85fa-5f006cfb965c.png)

```text
apm-server_1     | {"log.level":"error","@timestamp":"2022-07-19T21:23:08.098Z","log.logger":"kibana","log.origin":{"file.name":"kibana/connecting_client.go","file.line":79},"message":"failed to obtain connection to Kibana: fail to get the Kibana version: HTTP GET request to https://kibana:5601/api/status fails: fail to execute the HTTP GET request: Get \"https://kibana:5601/api/status\": x509: certificate signed by unknown authority. Response: ","service.name":"apm-server","ecs.version":"1.6.0"}

apm-server_1     | {"log.level":"error","@timestamp":"2022-07-19T21:23:37.614Z","log.logger":"beater","log.origin":{"file.name":"beater/waitready.go","file.line":64},"message":"precondition failed: EOF","service.name":"apm-server","ecs.version":"1.6.0"}
```

![Screenshot 2022-07-20 042824](https://user-images.githubusercontent.com/5449841/179851702-302bfddf-9e25-40fc-8b34-50a375137cc2.png)

so what I'm missing with this config, there's anyone who successfully adds an APM server?
