### ISSUE TITLE
Fleet server + Agent option

### ISSUE THREAD

**Issue by jeremywgleeson** [sherifabdlnaby/elastdocker#111]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem. I wanted to use [Fleet + Elastic Agents](https://www.elastic.co/guide/en/fleet/current/fleet-overview.html) to more easily collect metrics + logs and this not currently supported.

**Describe the solution you'd like**
 Provide a Fleet server service definition that users can enable instead of the APM server.

**Describe alternatives you've considered**
Continue letting users roll their own Fleet configuration.

**Additional context**
*Implementation suggestion:*
[Docker compose profiles](https://docs.docker.com/compose/profiles/) could be a nice way to implement this and would allow all core services to exist in the same compose file.

**Comment by GelsonTJunior** [comment]
I'm facing the same problem, I currently use the elastdocker stack, but I'm not able to link fleet-angent with the stack.

if you can help

**Comment by derekbking** [comment]
Spent some time getting this working today. Here's a snippet from my docker-compose:

```
    fleet-server:
        image: docker.elastic.co/elastic-agent/elastic-agent:${ELK_VERSION}
        container_name: fleet-server
        restart: always
        user: root
        ports:
            - "8220:8220"
        environment:
            FLEET_SERVER_ENABLE: true
            FLEET_SERVER_ELASTICSEARCH_HOST: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
            FLEET_SERVER_SERVICE_TOKEN: ${FLEET_SERVER_SERVICE_TOKEN}
            FLEET_SERVER_PORT: ${FLEETSERVER_PORT:-8220}
            FLEET_SERVER_ELASTICSEARCH_CA: /certs/ca.crt
        secrets:
            - source: elastic.ca
              target: /certs/ca.crt
```

Screenshot of my Fleet server policy. I have SSL setup on my load balancer in AWS. You may need to trust the ca configured by elastdocker docker if it's not signed by an official CA.
![image](https://github.com/user-attachments/assets/d9b435f5-e6be-441e-a94b-e722860c8c54)

**Comment by ElvisIsKing666** [comment]
I'm using 8.18.1 - I had to add some more env vars to my docker compose setup:
```yml
  fleet-server:
    image: ${ELASTIC_AGENT_IMAGE_NAME}:${ELK_VERSION}
    container_name: fleet-server
    restart: unless-stopped
    privileged: true
    environment:
      FLEET_SERVER_ENABLE: "1"
      FLEET_SERVER_ELASTICSEARCH_HOST: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      ELASTICSEARCH_CA: /ca/ca.crt
      FLEET_SERVER_POLICY_ID: "fleet-server-policy"
      FLEET_ENROLL: "1"
      FLEET_URL: https://${FLEET_SERVER_HOST}:8220
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_FLEET_SETUP: "1"
      KIBANA_HOST: https://${KIBANA_HOST}:${KIBANA_PORT}
      KIBANA_CA: /ca/ca.crt
      CERTIFICATE_AUTHORITIES: /ca/ca.crt
    volumes:
      - ./secrets/certs/fleet-server:/certs:ro
      - ./secrets/certs/ca/ca.crt:/ca/ca.crt:ro
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "${FLEET_SERVER_PORT}:${FLEET_SERVER_PORT}"
```

also, I had to modify `setup/instance.yml` to generate certs for the fleet-server:
```yml
  - name: fleet-server
    dns:
      - fleet-server
      - localhost
    ip:
      - 127.0.0.1
```

Changed the Makefile so it would start the fleet-server:
```
ELK_SERVICES   := elasticsearch logstash kibana apm-server fleet-server
```
