### ISSUE TITLE
Add Let's Encrypt to Elastdocker

### ISSUE THREAD

**Issue by sherifabdlnaby** [sherifabdlnaby/elastdocker#23]
#22 
> In your screenshots, your chrome shows "Not Secure", presumably because of the self signed certificate. A more thorough approach would be to add let's encrypt to the repo and allow auto-issuing certificates automatically when the cluster is spun up. Tools like Caprover to this to great effect.

**Comment by amitkurud** [comment]
Do you need help with this?

**Comment by sherifabdlnaby** [comment]
I haven't been having enough time to add it to Elastdocker myself, any help would be appreciated of course ❤️

**Comment by amitkurud** [comment]
ok , did you have something in mind on how it should be done ?

**Comment by amitkurud** [comment]
i was thinking using certbot and creating `make setup-letsencrypt` then compiling in directory to create certs. or do you have some other idea  ?

**Comment by wallopthecat** [comment]
Example of how someone else did it: https://github.com/swimlane/elk-tls-docker

**Comment by helgetan** [comment]
would like to push this topic:) Any plans here?

**Comment by lawndoc** [comment]
Another year, another person interested in this feature :) I'm swamped through Monday but if I get some free time next week I might look into [elk-tls-docker's implementation](https://github.com/swimlane/elk-tls-docker/wiki/Letsencrypt%20Walkthrough) as @wallopthecat mentioned and see if I can finally make a PR for this.

**Comment by lawndoc** [comment]
No longer Monday, but I did not forget about this. It's on my to-do list.

**Comment by ThrownLemon** [comment]
+1 also looking for a solution for this.

**Comment by lawndoc** [comment]
I'm back with an idea, and would like some input from repo maintainers on if they think this is a good solution.

I have tested a docker-compose setup that uses the official certbot container to auto-generate certs. Certbot shares a volume with nginx, and nginx uses the files put in that volume by certbot for TLS. Below is an example configuration:

```yaml
services:
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./volumes/certbot/conf/:/etc/letsencrypt/
      - ./volumes/certbot/www/:/var/www/certbot/
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/certbot/conf/:/etc/letsencrypt/
      - ./volumes/certbot/www/:/var/www/certbot/
    environment:
      EMAIL: ${EMAIL}
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
```

What do you all think about this solution? Is this the right direction to start in?
