### ISSUE TITLE
Using public certificate

### ISSUE THREAD

**Issue by TheoJL** [sherifabdlnaby/elastdocker#55]
Really like this repo and works very good out of the box! 

But can't figure out how to make it work with Lets Encrypt certs. I think I'm doing something really wrong.  Both Docker and ELK stack are very new to me. 

So I've copied all certs to the `/secret` folder with generous permissions. 
And then mapping them in `docker.compose.yml`

```
secrets:
  elasticsearch.keystore:
    file: ./secrets/keystore/elasticsearch.keystore
  elastic.ca:
    file: ./secrets/certs/elkdemo.demo123.com/fullchain.pem
  elasticsearch.certificate:
    file: ./secrets/certs/elkdemo.demo123.com/fullchain.pem
  elasticsearch.key:
    file: ./secrets/certs/elkdemo.demo123.com/privkey.pem
  kibana.certificate:
    file: ./secrets/certs/elkdemo.demo123.com/fullchain.pem
  kibana.key:
    file: ./secrets/certs/elkdemo.demo123.com/privkey.pem
```

Running with this I get

> logstash_1       | [2022-01-18T18:30:07,979][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elastic:xxxxxx@elasticsearch:9200/]}}
logstash_1       | [2022-01-18T18:30:08,026][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Host name 'elasticsearch' does not match the certificate subject provided by the peer (CN=elkdemo.demo123.com)"}

In browser `https://elkdemo.demo123.com:5601` it gets correct certs but with message "Kibana server is not ready yet"

Elasticsearch seems working
```
curl -X GET 'https://elkdemo.demo123.com:9200' -u elastic:changeme
{
  "name" : "elastdocker-node-0",
  "cluster_name" : "elastdocker-cluster",
  "cluster_uuid" : "1JA8zEeMS3aRlUw7xgTbGA",
  "version" : {
    "number" : "7.16.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "2b937c44140b6559905130a8650c64dbd0879cfb",
    "build_date" : "2021-12-18T19:42:46.604893745Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Tried changing in `kibana.yml` with same errors
from `elasticsearch.hosts: [ "${ELASTICSEARCH_HOST_PORT}" ]`
to `elasticsearch.hosts: [ "https://elkdemo.demo123.com:9200" ]`

Everything else is default using the latest commits.

Should I change ELASTICSEARCH_HOST, KIBANA_HOST and LOGSTASH_HOST in `.env` to my hostname, `elkdemo.demo123.com` ?
